### ISSUE TITLE
Keyboard Visual Suggestions Bug

### ISSUE THREAD

**Issue by Mikuana** [CoughDrop/coughdrop#1]
Found an issue where manually typing the word "worst" on the keyboard causes the suggestion "worst" to be repeated twice in the resulting suggestion list. Clicking the first suggestion (going from left to right) causes the word "worst" to be selected, but clicking the second suggestion will actually select the word "worse", despite the fact that the app is displaying the word "worst" in the list.

A possibly related bug can be replicated by typing the word "flame". This results in the word "flame" being displayed in the 1st and 5th position in the suggestion list. This differs from above in that the selected word is "flame" if you actually click on either suggestion.

**Comment by whitmer** [comment]
This appears to be resolve with a recent update. I'll leave it open for a bit in case you're still running into it, but I'm not seeing it in our production environment.
